import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from '../app/provider'; 
import AuthProvider from "@/utils/AuthProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function  RootLayout({ children }) {
  return (
    <html lang="en">
       <ReduxProvider> 
        <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      </AuthProvider>
      </ReduxProvider>
      
    </html>
  );
}


// 'use client';
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ReduxProvider from "../app/provider";
// import AuthProvider from "@/utils/AuthProvider";
// import Header from "@/components/partials/Header";
// import { useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//     const [isSidebarOpen, setSidebarOpen] = useState(false);
  
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50 text-black dark:bg-gray-900 dark:text-white`}
//       >
//         <ReduxProvider>
//           <AuthProvider>
//             <Header 
//                  isSidebarOpen={isSidebarOpen}
//                  onSidebarToggle={(state) => setSidebarOpen(state)}/>
//             <main
//         className={`p-6 transition-all duration-300 ${
//           isSidebarOpen ? "ml-64" : "ml-0"
//         }`}
//       >{children}</main>
//           </AuthProvider>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }
