"use client";
 export const permissionOptions = [
    { label: 'Can Add Company', value: 1 },
    { label: 'Can Edit Company', value: 2 },
    { label: 'Can Delete Company', value: 4 },
    { label: 'Can Read Company', value: 8 },
    { label: 'Can Add Client', value: 16 },
    { label: 'Can Edit Client', value: 32 },
    { label: 'Can Delete Client', value: 64 },
    { label: 'Can Read Client', value: 128 },
    { label: 'Can Add Subscription', value: 256 },
    { label: 'Can Edit Subscription', value: 512 },
    { label: 'Can Delete Subscription', value: 1024 },
    { label: 'Can Read Subscription', value: 2048 },
    { label: 'Can Edit Agent Percentage', value: 4096 },
    { label: 'Can Add Agent', value: 8192 },
    { label: 'Can Edit Agent', value: 16384 },
    { label: 'Can Delete Agent', value: 32768 },
    { label: 'Can Read Agent', value: 65536 },
    { label: 'Is Admin', value: 131072 },
  ];